#Screen
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

#Asteroids
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.5  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

#Player
PLAYER_RADIUS= 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOT_COOLDOWN = 0.1

#Projectiles
NORMAL_SHOT_RADIUS = 2
BIG_SHOT_RADIUS = 6
BIGGER_SHOT_RADIUS = 15
CHEATING_SHOT_RADIUS = 100


# OTHER
CYCLABLE_AMMO_TYPES = ["normal", "big", "bigger", "cheating"]